src/Entity/Kinkster.php
<?php

namespace App\Entity;

use App\Repository\KinksterRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

#[ORM\Entity(repositoryClass: KinksterRepository::class)]
#[UniqueEntity(fields: ['email'], message: 'There is already an account with this email')]
class Kinkster implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 180, unique: true)]
    private ?string $email = null;

    #[ORM\Column]
    private array $roles = [];

    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    private ?string $password = null;

    #[ORM\Column(length: 50)]
    private ?string $pseudo = null;

    #[ORM\Column(length: 255, unique: true)]
    private ?string $userSlug = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $description = null; 

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $creation = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $updateAt = null;

    #[ORM\Column]
    private ?bool $isFr = null;

    #[ORM\Column]
    private ?bool $isLetter = null;

    #[ORM\Column]
    private ?bool $isValidated = null;

    #[ORM\Column]
    private ?bool $isSuspended = null;

    #[ORM\Column]
    private ?bool $isDeleted = null;

    #[ORM\Column(nullable: true)]
    private ?bool $isKnown = null;

    #[ORM\Column(nullable: true)]
    private ?int $visit = null;

    #[ORM\OneToMany(mappedBy: 'kinkster', targetEntity: Impact::class)]
    private Collection $impacts;

    #[ORM\ManyToOne(inversedBy: 'users')]
    private ?Avatar $avatar = null;

    #[ORM\OneToMany(mappedBy: 'Kinkster', targetEntity: Visit::class)]
    private Collection $visits;

    #[ORM\ManyToOne(inversedBy: 'kinksters')]
    private ?Position $position = null;

    #[ORM\ManyToOne(inversedBy: 'kinkter')]
    private ?Fetish $fetish = null;

    #[ORM\OneToMany(mappedBy: 'user', targetEntity: Comment::class)]
    private Collection $comments;

    #[ORM\Column(length: 100, nullable: true)]
    private ?string $securityToken = null;

    #[ORM\ManyToMany(targetEntity: Cercle::class, mappedBy: 'kinksters')]
    private Collection $cercles;

    #[ORM\OneToMany(mappedBy: 'kinkster', targetEntity: ForumMsg::class)]
    private Collection $forumMsgs;



    // #[ORM\OneToMany(mappedBy: 'kinkster', targetEntity: TestComment::class)]
    // private Collection $testComments;


    public function __construct()
    {
        $this->impacts = new ArrayCollection();
        // $this->imageUsers = new ArrayCollection();
        // $this->rooms = new ArrayCollection();
        // $this->messagesSended = new ArrayCollection();
        // $this->testComments = new ArrayCollection();
        $this->visits = new ArrayCollection();
        $this->comments = new ArrayCollection();
        $this->cercles = new ArrayCollection();
        $this->forumMsgs = new ArrayCollection();
    }

    public function __toString()
    {
        return $this->getPseudo();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getPseudo(): ?string
    {
        return $this->pseudo;
    }

    public function setPseudo(string $pseudo): self
    {
        $this->pseudo = $pseudo;

        return $this;
    }

    public function getCreation(): ?\DateTimeInterface
    {
        return $this->creation;
    }

    public function setCreation(\DateTimeInterface $creation): self
    {
        $this->creation = $creation;

        return $this;
    }

    public function getUpdateAt(): ?\DateTimeInterface
    {
        return $this->updateAt;
    }

    public function setUpdateAt(\DateTimeInterface $updateAt): self
    {
        $this->updateAt = $updateAt;

        return $this;
    }


    /**
     * @return Collection<int, Impact>
     */
    public function getImpacts(): Collection
    {
        return $this->impacts;
    }

    public function addImpact(Impact $impact): self
    {
        if (!$this->impacts->contains($impact)) {
            $this->impacts->add($impact);
            $impact->setKinkster($this);
        }

        return $this;
    }

    public function removeImpact(Impact $impact): self
    {
        if ($this->impacts->removeElement($impact)) {
            // set the owning side to null (unless already changed)
            if ($impact->getKinkster() === $this) {
                $impact->setKinkster(null);
            }
        }

        return $this;
    }



    public function isIsValidated(): ?bool
    {
        return $this->isValidated;
    }

    public function setIsValidated(bool $isValidated): self
    {
        $this->isValidated = $isValidated;

        return $this;
    }

    public function isIsSuspended(): ?bool
    {
        return $this->isSuspended;
    }

    public function setIsSuspended(bool $isSuspended): self
    {
        $this->isSuspended = $isSuspended;

        return $this;
    }

    public function isIsDeleted(): ?bool
    {
        return $this->isDeleted;
    }

    public function setIsDeleted(bool $isDeleted): self
    {
        $this->isDeleted = $isDeleted;

        return $this;
    }

    public function getUserSlug(): ?string
    {
        return $this->userSlug;
    }

    public function setUserSlug(string $userSlug): self
    {
        $this->userSlug = $userSlug;

        return $this;
    }

    public function isIsFr(): ?bool
    {
        return $this->isFr;
    }

    public function setIsFr(bool $isFr): self
    {
        $this->isFr = $isFr;

        return $this;
    }

    public function isIsLetter(): ?bool
    {
        return $this->isLetter;
    }

    public function setIsLetter(bool $isLetter): self
    {
        $this->isLetter = $isLetter;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getVisit(): ?int
    {
        return $this->visit;
    }

    public function setVisit(?int $visit): self
    {
        $this->visit = $visit;

        return $this;
    }

    public function getAvatar(): ?Avatar
    {
        return $this->avatar;
    }

    public function setAvatar(?Avatar $avatar): self
    {
        $this->avatar = $avatar;

        return $this;
    }

    public function isIsKnown(): ?bool
    {
        return $this->isKnown;
    }

    public function setIsKnown(?bool $isKnown): self
    {
        $this->isKnown = $isKnown;

        return $this;
    }

    /**
     * @return Collection<int, Visit>
     */
    public function getVisits(): Collection
    {
        return $this->visits;
    }

    public function addVisit(Visit $visit): self
    {
        if (!$this->visits->contains($visit)) {
            $this->visits->add($visit);
            $visit->setKinkster($this);
        }

        return $this;
    }

    public function removeVisit(Visit $visit): self
    {
        if ($this->visits->removeElement($visit)) {
            // set the owning side to null (unless already changed)
            if ($visit->getKinkster() === $this) {
                $visit->setKinkster(null);
            }
        }

        return $this;
    }

    public function getPosition(): ?Position
    {
        return $this->position;
    }

    public function setPosition(?Position $position): self
    {
        $this->position = $position;

        return $this;
    }

    public function getFetish(): ?Fetish
    {
        return $this->fetish;
    }

    public function setFetish(?Fetish $fetish): self
    {
        $this->fetish = $fetish;

        return $this;
    }

    /**
     * @return Collection<int, Comment>
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments->add($comment);
            $comment->setUser($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): self
    {
        if ($this->comments->removeElement($comment)) {
            // set the owning side to null (unless already changed)

src/Controller/SecurityController.php
<?php

namespace App\Controller;

use App\Form\SearchEmailType;
use App\Form\RenewPasswordType;
use App\Repository\KinksterRepository;
use App\Service\MailerService;
use Doctrine\ORM\EntityManager;
use Doctrine\ORM\EntityManagerInterface;
use Doctrine\ORM\Mapping\Entity;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Session\SessionInterface;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Http\Authentication\AuthenticationUtils;
use Symfony\Component\PasswordHasher\Hasher\UserPasswordHasherInterface;

class SecurityController extends AbstractController
{

    #[Route(path: '/cellardoor', name: 'app_cellar_door')]
    public function login(
        AuthenticationUtils $authenticationUtils,
        SessionInterface $session,
        ): Response
    {   

        $lang = $session->get('lang');
        if ($this->getUser()) {
            return $this->redirectToRoute('app_home');
        }

        // get the login error if there is one
        $error = $authenticationUtils->getLastAuthenticationError();
        // last username entered by the user
        $lastUsername = $authenticationUtils->getLastUsername();

        return $this->render('security/login.html.twig', ['last_username' => $lastUsername, 'error' => $error, 'lang' => $lang]);
    }


    #[Route(path: '/sundown', name: 'app_sun_down')]
    public function logout(): void
    {
        throw new \LogicException('This method can be blank - it will be intercepted by the logout key on your firewall.');
    }

    #[Route(path: '/naty-boy/{code}', name: 'app_cop')]
    public function denyBoard(
        string $code,
    ): Response
    {

        return $this->render('front/cop/copFR.html.twig', [
            'controller_name' => 'TestController',
            'code' => $code,
        ]);
    }
    
    #[Route(path: '/security/reset-password', name: 'app_reset_password')]
    public function searchEmail(
        Request $request,
        KinksterRepository $kinsterRepository,
        MailerService $mailer,
        EntityManagerInterface $entityManager,
    ): Response
    {
        $message = '';
        $form = $this->createForm(SearchEmailType::class);
        $form->handleRequest($request);
        
        if ($form->isSubmitted() && $form->isValid()) {
            $data = $form->getData();

            // 1) Lookup the user by email
            $user = $kinsterRepository->findOneBy(['email' => $data['email']]);

            if (!$user) {
                // No user found, return error response
                $message = 'Email non trouvé.';
                return $this->render('security/findEmail.html.twig', [
                    'form' => $form,
                    'message' => $message,
                ]);
            } else {
                // Générer 16 octets aléatoires 
                $randomBytes = random_bytes(16);
                // Ajouter la composante temps
                $timestamp = time();
                // Concaténer et encoder en base64  
                $baseString = base64_encode($randomBytes . $timestamp);
                // Remplacer certains caractères
                $baseString = str_replace(['+', '/', '='], ['-', '_', ''], $baseString);
                // Token final de 64 caractères
                $securityToken = substr($baseString, 0, 64);
                // Enregistrer le token dans la base de données
                $user->setSecurityToken($securityToken);
                $entityManager->persist($user);
                $entityManager->flush();

                $message = 'Un email vous a été envoyé, cliquez sur le lien pour renouveler votre mot de passe. Pensez à regarder dans vos spams. / 
                 An email has been sent to you, click on the link to renew your password. Remember to check your spam.';
                            // do anything else you need here, like send an email
                $to = $form->get('email')->getData();
                $subject = 'Renouvellement mot de passe / Renew password : INSIDIOME';
                $token = $securityToken;
                $mailer->RenewPassordEmail($to, $subject, $token);
                return $this->render('security/findEmail.html.twig', [
                    'form' => $form,
                    'message' => $message,
                ]);
            }

        }

        return $this->render('security/findEmail.html.twig', [
            'form' => $form,
            'message' => $message,
        ]);
    }


    #[Route(path: '/security/new-password/{token}', name: 'app_renew_password')]
    public function renewPassword(
        string $token,
        Request $request,
        KinksterRepository $kinsterRepository,
        EntityManagerInterface $entityManager,
        UserPasswordHasherInterface $userPasswordHasher, 
    ): Response
    {
        
        $form = $this->createForm(RenewPasswordType::class);
        $form->handleRequest($request);
        
        if ($form->isSubmitted() && $form->isValid()) {
            // Récupérer l'utilisateur par le token
            $user = $kinsterRepository->findOneBy (['securityToken' => $token]);
            $user->setPassword(
                $userPasswordHasher->hashPassword(
                    $user,
                    $form->get('plainPassword')->getData()
                )
            );
            $user->setSecurityToken(null);

            $entityManager->persist($user);
            $entityManager->flush();

            // Rediriger vers la page de connexion
            return $this->redirectToRoute('app_cellar_door');
        }

        return $this->render('security/resetPassword.html.twig', [
            'form' => $form,
            'message' => 'Veuillez renseigner votre nouveau mot de passe',

        ]);
    }

    
}

templates/security/findEmail.html.twig
{% extends 'new-base.html.twig' %}



{% block stylesheets %}
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    {{ encore_entry_link_tags('general') }}
    <style>

    </style>   
{% endblock %}

{% block javascripts %}
    {{ encore_entry_script_tags('app') }}
    {# {{ encore_entry_script_tags('popModal') }} #}

{% endblock %}

{% block body %}
    {% include "front/partials/asideUp.html.twig" 
        with {
            imgBack: "build/img/gen/cop1.jpg",
        } 
    %}
    {% include "front/partials/asideDown.html.twig" %}

    <main class="main__container relative vh100">
        {# ------------------------------------------------------------ #}
        <section id="1" class="section__major bk-drk2 shdw-in-D">
            <div class="mobile__img__bk shdw-in-D" style="background-image: url('{{ asset('build/img/gen/cop1.jpg') }}');" >
            <div>
        </section>
        {# ------------------------------------------------------------ #}
        <div class="modl" id="popModal" >
            <div class="modl__content padx1 pady3 mar1">
                <h1 class="title2 txt-second">Reset Password</h1>
                <p class="info1 txt-warn">{{message}}</p>
                {{ form_start(form, {'attr': {'class': 'fluidx'}}) }}
                    <span class="info1 txt-prim-light">Entrez votre email / Enter your email</span>
                    {{ form_row(form.email) }}
                    <button class="butn butn-prim">{{ button_label|default('enregister') }}</button>
                {{ form_end(form) }}
            </div>
        </div>
    </main>
 
{% endblock %}

templates/security/login.html.twig
{% extends 'new-base.html.twig' %}


    {% block title %}INSIDIOME - ENTER{% endblock %}
    {% block og_title %}INSIDIOME - ENTER{% endblock %}

    {% block description %}Page d'entrée du site INSIDIOME - chox de la langue / Entrance page of the INSIDIOME site - choice of language{% endblock %}
    {% block og_description %}Page d'entrée du site INSIDIOME - chox de la langue / Entrance page of the INSIDIOME site - choice of language{% endblock %}

    {% block keywords %}insidiome, bdsm, life style, lifestyle, life-style, life, style, lifesty{% endblock %}

    {% block canonical %}https://insidiome.fr{% endblock %}
    {% block og_link %}https://insidiome.fr{% endblock %}

    {% block og_image %}https://www.insidiome.com/build/img/gen/room1.jpg{% endblock %}

    {% block og_type %}website{% endblock %}
    {% block og_locale %}fr_FR{% endblock %}

    {% block robots %}index,follow{% endblock %}


{% block stylesheets %}
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    {{ encore_entry_link_tags('general') }}
    <style>

    </style>   
{% endblock %}

{% block javascripts %}
    {{ encore_entry_script_tags('app') }}
    {# {{ encore_entry_script_tags('popModal') }} #}

{% endblock %}

{% block body %}
    {% include "front/partials/asideUp.html.twig" 
        with {
            imgBack: "build/img/gen/back1.jpg",
        } 
    %}
    {% include "front/partials/asideDown.html.twig" %}

    <main class="main__container relative vh100">
        {# ------------------------------------------------------------ #}
        <section id="1" class="section__major bk-drk2 shdw-in-D">
            <div class="mobile__img__bk shdw-in-D" style="background-image: url('{{ asset('build/img/gen/back1.jpg') }}');" >
            <div>
        </section>
        {# ------------------------------------------------------------ #}
        <div class="modl" id="popModal" >
            <div class="modl__content padx1 pady3 mar1">
                {% if error %}
                    <div class="alert alert-danger">{{ error.messageKey|trans(error.messageData, 'security') }}</div>
                {% endif %}

                {% if app.user %}
                    <div class="mb-3">
                        You are logged in as {{ app.user.userIdentifier }}, <a href="{{ path('app_sun_down') }}">Logout</a>
                    </div>
                {% endif %}
                <h1 class="title1 txt-second ">Connexion</h1>
                {# <h2 class="sub-title2 txt-soft">Entrez vos identifiants</h2> #}
                <hr class="hr-soft">
                <form method="post">
                    {# <label class="form-label" for="inputEmail">Email</label> #}
                    <div class="info1 txt-prim-light">Email</div>
                    <input type="email" value="{{ last_username }}" name="email" id="inputEmail" class="form-control" autocomplete="email" required autofocus>
                    {# <label class="form-label" for="inputPassword">Password</label> #}
                    <div class="info1 txt-prim-light">Password</div>
                    <input type="password" name="password" id="inputPassword" class="form-control" autocomplete="current-password" required>
                    {# <label class="form-label" for="inputPassword"> #}
                    {# <input type="checkbox" name="_remember_me">Remember me / Se souvenir de moi</label> #}

                    <input type="hidden" name="_csrf_token" value="{{ csrf_token('authenticate') }}">
                    <button class="butn butn-prim mar1" type="submit">
                        Connexion
                    </button>
                </form> 
                <hr class="hr-soft">
                <p class="sub-title3 txt-soft">Mot de passe oublié ? / Forgot your password ?</p>
                <a href="{{ path('app_reset_password') }}" class="butn butn-prim mar1">Reset</a>
                <hr class="hr-soft">
                {# <h2 class="title3 txt-second ">Créer un compte <br> Create an account</h1>
                <h3 class="sub-title3 txt-soft">Rapide et sécurisé / Fast and secured</h2>
                <a href="{{ path('app_dungeon_gate') }}" class="butn butn-prim mar1"> Compte / Account</a> #}

            </div>
        </div>
    </main>
 
{% endblock %}

templates/security/no.html.twig
{% extends 'main.html.twig' %}

{# {% block title %}Log in!{% endblock %} #}

{% block body %}



    <div class="column__container">
        <div class="column__trunk">
            <div class="">
                <img src="{{ asset('build/img/gen/mobile.jpg') }}" alt="">
                <div class="column__content m-5">

                </div>    
            </div>
        </div>
    </div>

    <!-- Modal -->
<div class="modal banner__modal fade" id="pageModal" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="p-3">
                <h2 class="text-danger">Vous n'etes pas autorisé à acceder à ces données !</h2>
                
                {# <hr>
                <a href="" class="btn btn-outline-light">Mot de passe oublié ?</a>
                </div> #}
            </div>
        </div>
    </div>
</div> 

{% endblock %}

templates/security/resetPassword.html.twig
{% extends 'new-base.html.twig' %}



{% block stylesheets %}
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    {{ encore_entry_link_tags('general') }}
    <style>

    </style>   
{% endblock %}

{% block javascripts %}
    {{ encore_entry_script_tags('app') }}
    {# {{ encore_entry_script_tags('popModal') }} #}

{% endblock %}

{% block body %}
    {% include "front/partials/asideUp.html.twig" 
        with {
            imgBack: "build/img/gen/cop1.jpg",
        } 
    %}
    {% include "front/partials/asideDown.html.twig" %}

    <main class="main__container relative vh100">
        {# ------------------------------------------------------------ #}
        <section id="1" class="section__major bk-drk2 shdw-in-D">
            <div class="mobile__img__bk shdw-in-D" style="background-image: url('{{ asset('build/img/gen/cop1.jpg') }}');" >
            <div>
        </section>
        {# ------------------------------------------------------------ #}
        <div class="modl" id="popModal" >
            <div class="modl__content padx1 pady3 mar1">
                <h1 class="title3 txt-second">Reset Password</h1>
                <hr class="hr-soft">
                <p class="info1 txt-warn">{{message}}</p>
                {{ form_start(form, {'attr': {'class': 'fluidx'}}) }}
                    <span class="info1 txt-soft"></span>
                    {{ form_widget(form) }}
                    <button class="butn butn-prim">Enregistrer / Register</button>
                {{ form_end(form) }}
            </div>
        </div>
    </main>
 
{% endblock %}